export const providers = [
  {
    id: 1,
    name: "Sunshine Daycare Center",
    type: "Daycare Center",
    rating: 4.8,
    reviews: 120,
    price: "$$$",
    location: "Tribeca",
    address: "123 Sunny St, New York, NY 10013",
    coordinates: { lat: 40.7150, lng: -74.0090 },
    image: "https://images.unsplash.com/photo-1540479859555-17af45c78602?auto=format&fit=crop&q=80&w=400",
    tags: ["Full-time", "Ages 0-5", "Meals Included"],
    description: "A bright and nurturing environment for your little ones to grow and learn in the heart of Tribeca."
  },
  {
    id: 2,
    name: "Happy Hearts Home Childcare",
    type: "Home-based",
    rating: 4.9,
    reviews: 45,
    price: "$$",
    location: "West Village",
    address: "456 Quiet Ln, New York, NY 10014",
    coordinates: { lat: 40.7330, lng: -74.0030 },
    image: "https://images.unsplash.com/photo-1560510629-47607ede7567?auto=format&fit=crop&q=80&w=400",
    tags: ["Part-time", "Ages 1-4", "Outdoor Play"],
    description: "Warm, family-style care in a safe residential setting with a private garden."
  },
  {
    id: 3,
    name: "Little Explorers Preschool",
    type: "Preschool",
    rating: 4.7,
    reviews: 88,
    price: "$$$",
    location: "Upper West Side",
    address: "789 Knowledge Way, New York, NY 10024",
    coordinates: { lat: 40.7831, lng: -73.9712 },
    image: "https://images.unsplash.com/photo-1587653263995-422546a74559?auto=format&fit=crop&q=80&w=400",
    tags: ["Educational", "Ages 3-5", "Bilingual"],
    description: "Focusing on early childhood development through play and exploration near Central Park."
  },
  {
    id: 4,
    name: "Tiny Tots Nursery",
    type: "Nursery",
    rating: 4.6,
    reviews: 62,
    price: "$$",
    location: "Financial District",
    address: "321 Baby Steps Blvd, New York, NY 10004",
    coordinates: { lat: 40.7060, lng: -74.0080 },
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=400",
    tags: ["Infant Care", "Ages 0-2", "Flexible Hours"],
    description: "Specialized care for infants and toddlers with dedicated professionals in FiDi."
  },
  {
    id: 5,
    name: "Creative Kids After-School",
    type: "After-School",
    rating: 4.9,
    reviews: 34,
    price: "$",
    location: "Lower East Side",
    address: "555 Art Circle, New York, NY 10002",
    coordinates: { lat: 40.7180, lng: -73.9880 },
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&q=80&w=400",
    tags: ["Arts & Crafts", "Ages 5-12", "Homework Help"],
    description: "Inspiring creativity and supporting school-aged children after hours."
  },
  {
    id: 6,
    name: "Blueberry Hill Montessori",
    type: "Montessori",
    rating: 4.8,
    reviews: 75,
    price: "$$$$",
    location: "Chelsea",
    address: "888 Nature Path, New York, NY 10011",
    coordinates: { lat: 40.7450, lng: -74.0010 },
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&q=80&w=400",
    tags: ["Montessori", "Ages 2-6", "Eco-friendly"],
    description: "Cultivating independence and a love for learning in a natural environment in Chelsea."
  },
  {
    id: 7,
    name: "Park Slope Daycare",
    type: "Daycare Center",
    rating: 4.9,
    reviews: 92,
    price: "$$$",
    location: "Brooklyn",
    address: "222 Park Ave, Brooklyn, NY 11215",
    coordinates: { lat: 40.6710, lng: -73.9760 },
    image: "https://images.unsplash.com/photo-1594608661623-aa0bd3a69d98?auto=format&fit=crop&q=80&w=400",
    tags: ["Full-time", "Ages 1-5", "Organic Meals"],
    description: "Premium care with a focus on organic nutrition and outdoor exploration."
  },
  {
    id: 8,
    name: "Williamsburg Preschool",
    type: "Preschool",
    rating: 4.5,
    reviews: 56,
    price: "$$$",
    location: "Brooklyn",
    address: "444 River St, Brooklyn, NY 11249",
    coordinates: { lat: 40.7140, lng: -73.9660 },
    image: "https://images.unsplash.com/photo-1564429234817-2921bb33bb6a?auto=format&fit=crop&q=80&w=400",
    tags: ["Creative Arts", "Ages 3-5", "Music Program"],
    description: "A creative learning space in vibrant Williamsburg."
  }
];
