export const agencies = [
  { id: 1, 
    name: "Bright Horizons Agency",
    phone: "514-222-3333",
    email: "bright@gmail.com" },
  { id: 2, 
    name: "Childcare Connections",
    phone: "514-222-3333",
    email: "connection@gmail.com" },
  { id: 3, 
    name: "Children Choice",
    phone: "514-222-3333",
    email: "family@gmail.com" }
];

export const providers = [
  {
    id: 1,
    name: "Sunshine Daycare Center",
    type: "Daycare Center",
    rating: 4.8,
    reviews: 120,
    location: "Toronto",
    spotsAvailable: 5,
    maxCapacity: 15,
    AgesServed: ["Infant (0-17 months)", "Toddler (18 months - 2 yrs)", "Preschool (3 yrs - 4yrs)"],
    mealsProvided: true,
    snackProvided: true,
    registeredWithCity: true,
    image: "https://images.unsplash.com/photo-1540479859555-17af45c78602?auto=format&fit=crop&q=80&w=400",
    tags: ["Full-time", "Infant", "Preschool", "Overnight", "Open Holidays", "Meals Included", "Snacks Provided"],
    description: "A bright and nurturing environment for your little ones to grow and learn in the heart of Toronto."
  },
  {
    id: 2,
    name: "Happy Hearts Home Childcare",
    type: "Licensed Home-based",
    agencyId: 3,
    rating: 4.9,
    reviews: 45,
    location: "Montreal",
    spotsAvailable: 0,
    maxCapacity: 10,
    AgesServed: ["Toddler (18 months - 2 yrs)", "Preschool (3 yrs - 4yrs)"],
    mealsProvided: false,
    snackProvided: true,
    registeredWithCity: true,
    image: "https://images.unsplash.com/photo-1560510629-47607ede7567?auto=format&fit=crop&q=80&w=400",
    tags: ["Part-time", "Toddler", "Preschool", "Drop-in", "Outdoor Play", "Snacks Provided"],
    description: "Warm, family-style care in a safe residential setting with a private garden."
  },
  {
    id: 3,
    name: "Little Explorers Preschool",
    type: "Preschool",
    rating: 4.7,
    reviews: 88,
    location: "Ottawa",
    spotsAvailable: 3,
    maxCapacity: 12,
    AgesServed: ["Preschool (3 yrs - 4yrs)", "School (5 yrs and older)"],
    mealsProvided: false,
    snackProvided: true,
    registeredWithCity: true,
    image: "https://images.unsplash.com/photo-1587653263995-422546a74559?auto=format&fit=crop&q=80&w=400",
    tags: ["Educational", "Preschool", "Before School", "After School", "Bilingual", "Snacks Provided"],
    description: "Focusing on early childhood development through play and exploration near local parks."
  },
  {
    id: 4,
    name: "Tiny Tots Nursery",
    type: "Daycare Center",
    rating: 4.6,
    reviews: 62,
    location: "Quebec City",
    spotsAvailable: 2,
    maxCapacity: 10,
    AgesServed: ["Infant (0-17 months)", "Toddler (18 months - 2 yrs)"],
    mealsProvided: true,
    snackProvided: true,
    registeredWithCity: false,
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=400",
    tags: ["Infant", "Toddler", "Weekend", "Meals Provided", "Snacks Provided"],
    description: "Specialized care for infants and toddlers with dedicated professionals."
  },
  {
    id: 5,
    name: "Creative Kids After-School",
    type: "After-School",
    rating: 4.9,
    reviews: 34,
    location: "Winnipeg",
    spotsAvailable: 0,
    maxCapacity: 20,
    AgesServed: ["School (5 yrs and older)"],
    mealsProvided: false,
    snackProvided: true,
    registeredWithCity: true,
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&q=80&w=400",
    tags: ["Arts & Crafts", "School", "After School", "Snacks Provided"],
    description: "Inspiring creativity and supporting school-aged children after hours."
  },
  {
    id: 6,
    name: "Blueberry Hill Montessori",
    type: "Preschool",
    rating: 4.8,
    reviews: 75,
    location: "Edmonton",
    spotsAvailable: 8,
    maxCapacity: 25,
    AgesServed: ["Toddler (18 months - 2 yrs)", "Preschool (3 yrs - 4yrs)", "School (5 yrs and older)"],
    mealsProvided: false,
    snackProvided: false,
    registeredWithCity: false,
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&q=80&w=400",
    tags: ["Educational", "Ages 2-6", "Eco-friendly"],
    description: "Cultivating independence and a love for learning in a natural environment."
  },
  {
    id: 7,
    name: "Park Slope Daycare",
    type: "Daycare Center",
    rating: 4.9,
    reviews: 92,
    location: "Halifax",
    spotsAvailable: 4,
    maxCapacity: 15,
    AgesServed: ["Toddler (18 months - 2 yrs)", "Preschool (3 yrs - 4yrs)"],
    mealsProvided: true,
    snackProvided: true,
    registeredWithCity: true,
    image: "https://images.unsplash.com/photo-1594608661623-aa0bd3a69d98?auto=format&fit=crop&q=80&w=400",
    tags: ["Full-time", "Toddler", "Preschool", "Overnight", "Organic Meals", "Snacks Provided"],
    description: "Premium care with a focus on organic nutrition and outdoor exploration."
  },
  {
    id: 8,
    name: "Williamsburg Preschool",
    type: "Preschool",
    rating: 4.5,
    reviews: 56,
    location: "Victoria",
    spotsAvailable: 0,
    maxCapacity: 12,
    AgesServed: ["Preschool (3 yrs - 4yrs)"],
    mealsProvided: false,
    snackProvided: true,
    registeredWithCity: false,
    image: "https://images.unsplash.com/photo-1564429234817-2921bb33bb6a?auto=format&fit=crop&q=80&w=400",
    tags: ["Creative Arts", "Preschool", "Drop-in", "Snacks Provided"],
    description: "A creative learning space in vibrant Victoria."
  },
  {
    id: 9,
    name: "Calgary Kids Academy",
    type: "Daycare Center",
    rating: 4.9,
    reviews: 25,
    location: "Calgary",
    spotsAvailable: 6,
    maxCapacity: 30,
    AgesServed: ["Infant (0-17 months)", "Preschool (3 yrs - 4yrs)"],
    mealsProvided: true,
    snackProvided: true,
    registeredWithCity: true,
    image: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&q=80&w=400",
    tags: ["Full-time", "Infant", "Preschool", "Open Holidays", "Meals Provided", "Snacks Provided"],
    description: "A state-of-the-art learning center located in the heart of Calgary."
  },
  {
    id: 10,
    name: "Vancouver Early Years",
    type: "Preschool",
    rating: 4.7,
    reviews: 32,
    location: "Vancouver",
    spotsAvailable: 1,
    maxCapacity: 15,
    AgesServed: ["Preschool (3 yrs - 4yrs)", "School (5 yrs and older)"],
    mealsProvided: false,
    snackProvided: true,
    registeredWithCity: true,
    image: "https://images.unsplash.com/photo-1595206133361-b1fe343e5e23?auto=format&fit=crop&q=80&w=400",
    tags: ["Educational", "Preschool", "Before School", "Outdoor Learning", "Snacks Provided"],
    description: "Specialized preschool program focused on nature-based learning in Kitsilano."
  },
  {
    id: 11,
    name: "Rocky Mountain Montessori",
    type: "Preschool",
    rating: 4.8,
    reviews: 19,
    location: "Calgary",
    spotsAvailable: 0,
    maxCapacity: 10,
    AgesServed: ["Toddler (18 months - 2 yrs)", "Preschool (3 yrs - 4yrs)", "School (5 yrs and older)"],
    mealsProvided: false,
    snackProvided: false,
    registeredWithCity: true,
    image: "https://images.unsplash.com/photo-1566454544259-f4b94c3d758c?auto=format&fit=crop&q=80&w=400",
    tags: ["Educational", "Toddler", "Preschool", "School", "Weekend", "Nature Focused"],
    description: "Holistic Montessori education with a focus on independence and environmental stewardship in Sundance."
  }
  ,
  {
    id: 12,
    name: "Alina Dayhome",
    type: "Licensed Home-based",
    agencyId: 3,
    rating: 4.8,
    reviews: 19,
    location: "Calgary",
    spotsAvailable: 0,
    maxCapacity: 6,
    AgesServed: ["Toddler (18 months - 2 yrs)", "Preschool (3 yrs - 4yrs)", "School (5 yrs and older)"],
    mealsProvided: false,
    snackProvided: true,
    registeredWithCity: true,
    image: "https://images.unsplash.com/photo-1566454544259-f4b94c3d758c?auto=format&fit=crop&q=80&w=400",
    tags: ["Licensed Home-based", "Toddler", "Preschool", "School", "Drop-in", "Nature Focused", "Snacks Provided"],
    description: "Licensed Home-based education with a focus on independence and environmental stewardship in Cranston."
  }
];

export const addresses = [
  { id: 1, providerId: 1, fullAddress: "123 Sunny St, Toronto, ON M5V 2H1", province: "Ontario", city: "Toronto", community: "Downtown", coordinates: { lat: 43.6426, lng: -79.3871 } },
  { id: 2, providerId: 2, fullAddress: "456 Quiet Ln, Montreal, QC H3B 1A2", province: "Quebec", city: "Montreal", community: "Ville-Marie", coordinates: { lat: 45.5017, lng: -73.5673 } },
  { id: 3, providerId: 3, fullAddress: "789 Knowledge Way, Ottawa, ON K1P 5L1", province: "Ontario", city: "Ottawa", community: "Centretown", coordinates: { lat: 45.4215, lng: -75.6972 } },
  { id: 4, providerId: 4, fullAddress: "321 Baby Steps Blvd, Quebec City, QC G1R 4P5", province: "Quebec", city: "Quebec City", community: "Old Quebec", coordinates: { lat: 46.8139, lng: -71.2080 } },
  { id: 5, providerId: 5, fullAddress: "555 Art Circle, Winnipeg, MB R3C 1V1", province: "Manitoba", city: "Winnipeg", community: "Forks", coordinates: { lat: 49.8951, lng: -97.1384 } },
  { id: 6, providerId: 6, fullAddress: "888 Nature Path, Edmonton, AB T5J 2R7", province: "Alberta", city: "Edmonton", community: "Downtown", coordinates: { lat: 53.5461, lng: -113.4938 } },
  { id: 7, providerId: 7, fullAddress: "222 Park Ave, Halifax, NS B3J 1M5", province: "Nova Scotia", city: "Halifax", community: "Downtown", coordinates: { lat: 44.6488, lng: -63.5752 } },
  { id: 8, providerId: 8, fullAddress: "444 River St, Victoria, BC V8W 1P5", province: "BC", city: "Victoria", community: "Downtown", coordinates: { lat: 48.4284, lng: -123.3656 } },
  { id: 9, providerId: 9, fullAddress: "123 Calgary Trail, Calgary, AB T2P 2M5", province: "Alberta", city: "Calgary", community: "Beltline", coordinates: { lat: 51.0447, lng: -114.0719 } },
  { id: 10, providerId: 10, fullAddress: "789 Ocean Drive, Vancouver, BC V6J 1Z1", province: "BC", city: "Vancouver", community: "Kitsilano", coordinates: { lat: 49.2684, lng: -123.1678 } },
  { id: 11, providerId: 11, fullAddress: "45 Sundance Blvd, Calgary, AB T2X 2G1", province: "Alberta", city: "Calgary", community: "Sundance", coordinates: { lat: 50.9022, lng: -114.0483 } },
  { id: 12, providerId: 12, fullAddress: "24 cranberry lane se, Calgary, AB T3M 0L5", province: "Alberta", city: "Calgary", community: "Cranston", coordinates: { lat: 50.8834, lng: -113.9736 } }
];

export const spotsAvailable = [
  { id: 1, providerId: 1, AgeServed: "Infant (0-17 months)", partTime: 1, fullTime: 2, startDate: "2026-03-01" },
  { id: 2, providerId: 1, AgeServed: "Toddler (18 months - 2 yrs)", partTime: 0, fullTime: 2, startDate: "2026-04-01" },
  { id: 3, providerId: 3, AgeServed: "Preschool (3 yrs - 4yrs)", partTime: 1, fullTime: 2, startDate: "2026-02-15" },
  { id: 4, providerId: 4, AgeServed: "Infant (0-17 months)", partTime: 0, fullTime: 2, startDate: "2026-05-01" },
  { id: 5, providerId: 6, AgeServed: "Toddler (18 months - 2 yrs)", partTime: 2, fullTime: 2, startDate: "2026-03-15" },
  { id: 6, providerId: 6, AgeServed: "Preschool (3 yrs - 4yrs)", partTime: 2, fullTime: 2, startDate: "2026-03-15" },
  { id: 7, providerId: 7, AgeServed: "Toddler (18 months - 2 yrs)", partTime: 1, fullTime: 1, startDate: "2026-06-01" },
  { id: 8, providerId: 7, AgeServed: "Preschool (3 yrs - 4yrs)", partTime: 1, fullTime: 1, startDate: "2026-06-01" },
  { id: 9, providerId: 9, AgeServed: "Infant (0-17 months)", partTime: 2, fullTime: 2, startDate: "2026-04-15" },
  { id: 10, providerId: 9, AgeServed: "Preschool (3 yrs - 4yrs)", partTime: 1, fullTime: 1, startDate: "2026-04-15" },
  { id: 11, providerId: 10, AgeServed: "School (5 yrs and older)", partTime: 1, fullTime: 0, startDate: "2026-09-01" }
];
